CONTOUR_THRESHOLD = 100
ANGLE_DELTAS = [5, 10, 20, 30]
TOP_K_BASE_VERTICES = 20

CUT_DETECTION_DELTA = 10
CUT_DETECTION_START_IDX = 6
CUT_DETECTION_THRESHOLD = 10

FFT_FEATURES = 10
DIST_FUNCTION = lambda x1, x2: abs(x1 - x2).sum()
